# Generated by Django 4.2 on 2023-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordresult',
            name='mail',
            field=models.EmailField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp6',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp7',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recordresult',
            name='symp8',
            field=models.CharField(max_length=10),
        ),
    ]
