# Generated by Django 4.2 on 2023-05-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recordresult_drcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordresult',
            name='suggestion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
